# -*- coding: utf-8 -*-
"""mikolaj2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14wmV2UMVf1hCRFD5ToVgr6mc3Xu3tqho
"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import streamlit as st

# Ustawienie tytułu aplikacji Streamlit
st.title("Święty Mikołaj w Streamlit 🎅")

# Utworzenie figury i osi (jak wcześniej)
# Ważne: Zapisujemy referencję do figury 'fig'
fig, ax = plt.subplots(figsize=(6, 8))
ax.set_xlim(0, 10)
ax.set_ylim(0, 12)
ax.set_aspect('equal', adjustable='box')
ax.axis('off') # Ukrycie osi

# --- 1. Ciało Mikołaja (Czerwony Strój) ---
# Tors (prostokąt)
ax.add_patch(patches.Rectangle((3.5, 3.5), 3, 4, color='#B22222', alpha=0.9)) # Ciemnoczerwony

# Pas (czarny prostokąt)
ax.add_patch(patches.Rectangle((3.5, 5.0), 3, 0.5, color='black'))

# Klamra pasa (żółty kwadrat)
ax.add_patch(patches.Rectangle((4.7, 5.0), 0.6, 0.5, color='#FFD700')) # Złoty

# --- 2. Głowa i Broda ---
# Głowa (koło)
ax.add_patch(patches.Circle((5, 8), 1, color='#F0CC9C')) # Kolor skóry

# Broda (owal/koło pod głową)
ax.add_patch(patches.Ellipse((5, 7.5), 2.5, 1.8, color='white'))
ax.add_patch(patches.Circle((5, 7.5), 0.3, color='white')) # Dodatkowa biała "kępka" na nos i policzki

# Oczy (małe czarne kropki)
ax.add_patch(patches.Circle((4.5, 8.2), 0.08, color='black'))
ax.add_patch(patches.Circle((5.5, 8.2), 0.08, color='black'))

# --- 3. Czapka ---
# Czerwony stożek czapki (trójkąt)
ax.add_patch(patches.Polygon([[4, 9], [6, 9], [5.5, 11]], closed=True, color='red'))

# Biały pasek na dole czapki (prostokąt)
ax.add_patch(patches.Rectangle((3.9, 8.8), 2.2, 0.4, color='white'))

# Biały pompon na czubku czapki (koło)
ax.add_patch(patches.Circle((5.5, 11), 0.4, color='white'))

# --- 4. Prezenty (Worek) ---
# Worek na prezenty (brązowy prostokąt)
ax.add_patch(patches.Rectangle((6.5, 3.5), 2, 3, color='#8B4513', alpha=0.8)) # Brązowy

# Wystające prezenty (różnokolorowe kwadraty na wierzchu worka)
ax.add_patch(patches.Rectangle((6.8, 6.5), 0.5, 0.5, color='green'))
ax.add_patch(patches.Rectangle((7.5, 6.5), 0.5, 0.5, color='blue'))
ax.add_patch(patches.Rectangle((8.1, 6.5), 0.5, 0.5, color='yellow'))
ax.add_patch(patches.Rectangle((7.2, 6.8), 0.5, 0.5, color='purple')) # Wyżej

# Tekst "Ho Ho Ho!"
ax.text(5, 1, "Wesołych Świąt!", fontsize=16, ha='center', color='red')

# Ustawienie tytułu wykresu
ax.set_title("Święty Mikołaj w Matplotlib")

# --- KLUCZOWA ZMIANA: Wyświetlanie w Streamlit ---
# Zamiast plt.show() używamy st.pyplot() i przekazujemy mu obiekt figury
st.pyplot(fig)